import { Inter } from 'next/font/google'
import './globals.css'
import { GlobalProvider } from '../app/GlobalContext';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <GlobalProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </GlobalProvider>
  )
}
