"use client"
import { useState } from 'react';
import Header_Student from '../../components/Header_Student';

const blogs = [
    { id: 1, title: 'Google Interview Experience', author: 'Abhishek', content: "I'm thrilled to share my experience of interviewing with Google, one of the most renowned tech companies in the world! From the application process to the final interview rounds, it has been an incredible journey filled with challenges, learnings, and personal growth.The journey began with the initial application, where I had the opportunity to showcase my skills and experiences through my resume and cover letter. The process was smooth and well-organized, thanks to the clear communication and guidance from the Google recruitment team.As I progressed to the interview rounds, I was greeted with a series of technical assessments and coding challenges that pushed me to think critically and creatively. Each interview round provided me with valuable feedback and insights, allowing me to refine my skills and approach for the next round.One of the most memorable aspects of the interview process was the opportunity to engage with some of the brightest minds in the industry. The interviewers were not only experts in their respective fields but also genuinely passionate about helping candidates succeed. Their guidance and mentorship throughout the process were invaluable, and I'm incredibly grateful for the opportunity to learn from them.Finally, after several rounds of interviews, I received the news that I had been selected to join Google! The feeling of excitement and accomplishment was indescribable, knowing that I would soon be a part of a company that is at the forefront of innovation and technology." },
    { id: 2, title: 'Service Now Interview Experience', author: 'Sparsh & Abhishek', content: "I'm excited to share my experience of interviewing with ServiceNow, a leading company in the world of digital workflows and cloud computing. From the initial application to the final interview rounds, it has been an enlightening journey filled with valuable insights and personal development.The journey began with the initial application process, where I had the opportunity to showcase my skills, experiences, and passion for technology. ServiceNow's recruitment team provided clear communication and guidance throughout, making the process seamless and efficient.As I progressed to the interview rounds, I was presented with a series of technical assessments and discussions that challenged me to think critically and demonstrate my problem-solving abilities. Each interview round provided me with new perspectives and opportunities to showcase my expertise in areas such as cloud computing, IT service management, and software development.One of the most rewarding aspects of the interview process was the chance to engage with ServiceNow's talented and dedicated team members. From the interviewers to the hiring managers, everyone I interacted with demonstrated a genuine passion for their work and a commitment to fostering a culture of innovation and collaboration." },
    { id: 3, title: 'Saleforces Interview Experience', author: 'Deepshikha', content: "I'm excited to share my experience of interviewing with Salesforce, a pioneering company in cloud computing and customer relationship management (CRM). From the initial application to the final interview rounds, it has been an enlightening journey filled with valuable insights and personal development.The journey began with the initial application process, where I had the opportunity to showcase my skills, experiences, and passion for technology. Salesforce's recruitment team provided clear communication and guidance throughout, making the process seamless and efficient.As I progressed to the interview rounds, I was presented with a series of technical assessments and discussions that challenged me to think critically and demonstrate my problem-solving abilities. Each interview round provided me with new perspectives and opportunities to showcase my expertise in areas such as cloud computing, software development, and CRM solutions.One of the most rewarding aspects of the interview process was the chance to engage with Salesforce's talented and diverse team members. From the interviewers to the hiring managers, everyone I interacted with demonstrated a genuine passion for their work and a commitment to driving positive change in the world.Throughout the process, I received constructive feedback and support from the interviewers, which helped me refine my skills and approach for future rounds. Their guidance and encouragement motivated me to perform at my best and embrace every challenge as an opportunity for growth." },
    { id: 4, title: 'Dom Dog Working Experience', author: 'Lavesh', content: "I'm excited to share my journey of working in an information security company, where every day is a new opportunity to protect digital assets and mitigate cyber threats. From the dynamic challenges to the rewarding experiences, it has been an enriching journey filled with growth and learning.My role in the information security company has been multifaceted, involving a range of responsibilities aimed at ensuring the confidentiality, integrity, and availability of sensitive information. Whether it's conducting security assessments, implementing robust security controls, or responding to incidents, I've had the privilege of contributing to the organization's mission of safeguarding digital assets and building resilience against cyber threats.One of the most rewarding aspects of working in an information security company is the opportunity to collaborate with talented professionals from diverse backgrounds. From cybersecurity experts to risk analysts, everyone brings unique insights and perspectives to the table, fostering a culture of innovation and continuous improvement.In addition to the technical aspects of the job, I've also had the chance to develop soft skills such as communication, problem-solving, and critical thinking. Effective communication is crucial in conveying complex security concepts to stakeholders and promoting a culture of security awareness throughout the organization." },
{ id: 5, title: 'Microsoft Interview Experience', author: 'Rahul', content: "I'm thrilled to share my experience of interviewing with Microsoft, one of the leading technology companies globally. From the initial application to the final interview rounds, it has been an exhilarating journey filled with challenges and growth opportunities. The application process was rigorous yet transparent, with clear communication from the Microsoft recruitment team at every step. As I progressed through the interview rounds, I encountered a diverse range of technical assessments and problem-solving exercises that tested my knowledge and creativity. Each interview provided valuable insights and feedback, helping me refine my skills and prepare for the next stage. One of the highlights was the chance to interact with Microsoft's passionate and innovative employees, who demonstrated a genuine commitment to excellence and collaboration. Their guidance and mentorship were invaluable, and I'm grateful for the opportunity to learn from them. Finally, receiving the news of my acceptance into Microsoft was a moment of immense pride and excitement, knowing that I would be joining a company at the forefront of technology and innovation." },
    { id: 6, title: 'Amazon Interview Experience', author: 'Priya', content: "I'm excited to share my experience of interviewing with Amazon, a global leader in e-commerce, cloud computing, and digital streaming. From the initial application to the final interview rounds, it has been a challenging yet rewarding journey filled with growth and learning opportunities. The application process was thorough and well-organized, with clear instructions from the Amazon recruitment team. As I progressed through the interview stages, I encountered a variety of technical assessments and behavioral interviews that tested both my technical skills and cultural fit. Each interview provided valuable insights and feedback, allowing me to learn and improve with each round. One of the highlights was the opportunity to engage with Amazon's diverse and talented team members, who were passionate about their work and eager to help candidates succeed. Their support and guidance were instrumental in my success throughout the interview process. Receiving the news of my acceptance into Amazon was a moment of great joy and accomplishment, and I'm excited to join a company that values innovation, customer obsession, and excellence." },
    { id: 7, title: 'Apple Interview Experience', author: 'Karthik', content: "I'm thrilled to share my experience of interviewing with Apple, a world-renowned technology company known for its innovation and creativity. From the initial application to the final interview rounds, it has been an inspiring journey filled with challenges and growth opportunities. The application process was well-structured, with clear communication from the Apple recruitment team. As I progressed through the interview stages, I encountered a range of technical assessments and problem-solving exercises that pushed me to think critically and creatively. Each interview provided valuable insights and feedback, helping me refine my skills and prepare for the next stage. One of the highlights was the chance to interact with Apple's passionate and talented employees, who shared their experiences and insights into the company's culture and values. Their support and encouragement were invaluable, and I'm grateful for the opportunity to learn from them. Receiving the news of my acceptance into Apple was a dream come true, and I'm excited to join a company that is dedicated to pushing the boundaries of technology and design." },
    { id: 8, title: 'Tesla Interview Experience', author: 'Amit', content: "I'm excited to share my experience of interviewing with Tesla, a pioneering company in the automotive and renewable energy industries. From the initial application to the final interview rounds, it has been an exhilarating journey filled with challenges and learning opportunities. The application process was rigorous yet transparent, with clear communication from the Tesla recruitment team. As I progressed through the interview stages, I encountered a variety of technical assessments and problem-solving exercises that tested my knowledge and skills. Each interview provided valuable insights and feedback, allowing me to grow and improve with each round. One of the highlights was the opportunity to engage with Tesla's passionate and innovative team members, who shared their vision for the future and the company's commitment to sustainability. Their support and mentorship were invaluable, and I'm grateful for the opportunity to learn from them. Receiving the news of my acceptance into Tesla was a moment of great pride and excitement, and I'm thrilled to join a company that is leading the way in innovation and sustainability." }
];

export default function BlogPage() {
    const [selectedBlog, setSelectedBlog] = useState(null);

    const handleBlogClick = (blog) => {
        setSelectedBlog(blog);
    };

    return (
        <div className="min-h-screen bg-white text-black">
            <Header_Student />
            <main className="container mx-auto px-4 py-8">
                <h1 className="text-4xl font-bold mb-8 text-center">Blog Posts</h1>
                <div className="flex flex-col lg:flex-row gap-8">
                    <aside className="w-full lg:w-1/3">
                        <h2 className="text-2xl font-semibold mb-4 pb-2 border-b-2 border-gray-200">Latest Stories</h2>
                        <div className="space-y-4">
                            {blogs.map((blog) => (
                                <div
                                    key={blog.id}
                                    className="p-4 border border-gray-200 rounded-lg cursor-pointer transition-all hover:shadow-md"
                                    onClick={() => handleBlogClick(blog)}
                                >
                                    <h3 className="text-xl font-semibold mb-2">{blog.title}</h3>
                                    <p className="text-sm text-gray-600">By {blog.author}</p>
                                </div>
                            ))}
                        </div>
                    </aside>
                    <section className="w-full lg:w-2/3">
                        {selectedBlog ? (
                            <article className="border border-gray-200 rounded-lg p-6 shadow-sm">
                                <h2 className="text-3xl font-bold mb-4">{selectedBlog.title}</h2>
                                <p className="text-lg text-gray-600 mb-6">By {selectedBlog.author}</p>
                                <div className="prose max-w-none">
                                    <p>{selectedBlog.content}</p>
                                </div>
                            </article>
                        ) : (
                            <div className="flex items-center justify-center h-64 border border-gray-200 rounded-lg">
                                <p className="text-xl text-gray-500">Select a blog post to read</p>
                            </div>
                        )}
                    </section>
                </div>
            </main>
        </div>
    );
}

